name: Check setup container shell

on: [push]

jobs:
  check_setup_container_shell:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: shellcheck setup-container-shell
        shell: bash
        run: shellcheck bin/setup-container-shell.sh

      - name: run setup-container-shell tests
        shell: bash
        run: bash tests/test_setup_container_shell.sh
