name: Check bash

on: [push]


jobs:
  check_bash:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Debug this
        run: ls -ltra && pwd

      - name: Find all bash files by searching for shebang
        run: |
          echo BASH_FILES=$(grep -rn '.' -e "\#\!/bin/bash" | sed -r 's/:.*//g') >> $GITHUB_OUTPUT
        id: find_bash_files

      - name: Check bash
        run: |
          echo $bash_file && bash -c "source ${bash_file}"
        with:
          bash_file: ${{ steps.version.outputs.BASH_FILES }}

